FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY

ARG DATABASE_URL
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ENV DATABASE_URL=$DATABASE_URL
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME

ARG SUPABASE_SERVICE_ROLE_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY

ARG ALTEGIO_PARTNER_TOKEN
ARG ALTEGIO_USER_TOKEN
ARG ALTEGIO_COMPANY_ID
ARG ALTEGIO_WEBHOOK_SECRET
ENV ALTEGIO_PARTNER_TOKEN=$ALTEGIO_PARTNER_TOKEN
ENV ALTEGIO_USER_TOKEN=$ALTEGIO_USER_TOKEN
ENV ALTEGIO_COMPANY_ID=$ALTEGIO_COMPANY_ID
ENV ALTEGIO_WEBHOOK_SECRET=$ALTEGIO_WEBHOOK_SECRET

ARG SESSION_SECRET
ENV SESSION_SECRET=$SESSION_SECRET

COPY package*.json ./

RUN npm ci --include=dev

COPY . .

RUN npm run build

ENV NODE_ENV=production

EXPOSE 5000

CMD ["node", "dist/index.cjs"]
